language: python
python:
 - "2.7"
os:
 - linux
 - osx
env:
 - KERAS_VERSION=1.2.2
 - KERAS_VERSION=2.0.6
install: 
  - pip install -q Keras==$KERAS_VERSION
script:
 - pip setup.py bdist_wheel 
 - pip install dist/*.whl
 - nosetests -v ./testpackage/test
